import { ChatList } from 'modules/conversation/chats/model/chat.api.schema';

const now = Date.now() / 1000;

export const mockChatListApiResponse = {
  results: [
    // 1️⃣ Просто текст
    {
      id: 1,
      chat: {
        uid: '1',
        username: 'alex',
        nickname: 'alex',
        first_name: 'Alex',
        last_name: 'Ivanov',
        avatar_url: '/images/avatars/avatar-6.png',
        avatar_webp_url: '/images/profile/avatar.png',
        is_blocked: false,
        is_online: true,
        was_online_at: 0,
        is_in_contacts: true,
      },
      is_favorite: false,
      notifications: true,
      new_message_count: 0,
      name: 'Alex',
      chat_type: 'chat',
      chat_key: 'chat-1',
      last_activity_at: now,
      last_seen_message: { id: 1, uid: 'msg-1' },
      last_message: {
        id: 1,
        uid: 'msg-1',
        from_user: 'user-1',
        content: 'Привет! Как дела?',
        files_summary: null,
        has_replied_message: false,
        has_forwarded_message: false,
        new: false,
        created_at: now,
        updated_at: now,
      },
    },

    // 2️⃣ Только фото (3 превью)
    {
      id: 2,
      chat: {
        uid: '2',
        username: 'kate',
        nickname: 'kate',
        first_name: 'Kate',
        last_name: 'Brown',
        avatar_url: '/images/avatars/avatar-2.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: false,
        was_online_at: null,
        is_in_contacts: true,
      },
      is_favorite: false,
      notifications: false,
      new_message_count: 0,
      name: 'Kate',
      chat_type: 'chat',
      chat_key: 'chat-2',
      last_activity_at: now,
      last_seen_message: { id: 2, uid: 'msg-2' },
      last_message: {
        id: 2,
        uid: 'msg-2',
        from_user: 'user-2',
        content: '',
        files_summary: {
          types: ['image'],
          count: 3,
        },
        has_replied_message: false,
        has_forwarded_message: false,
        new: false,
        created_at: now,
        updated_at: now,
      },
    },

    // 3️⃣ Только видео
    {
      id: 3,
      chat: {
        uid: '3',
        username: 'mike',
        nickname: 'mike',
        first_name: 'Mike',
        last_name: 'Smith',
        avatar_url: '/images/avatars/avatar-3.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: false,
        was_online_at: now - 60,
        is_in_contacts: true,
      },
      is_favorite: false,
      notifications: true,
      new_message_count: 0,
      name: 'Mike',
      chat_type: 'chat',
      chat_key: 'chat-3',
      last_activity_at: now,
      last_seen_message: { id: 3, uid: 'msg-3' },
      last_message: {
        id: 3,
        uid: 'msg-3',
        from_user: 'user-3',
        content: '',
        files_summary: {
          types: ['video'],
          count: 1,
        },
        has_replied_message: false,
        has_forwarded_message: false,
        new: false,
        created_at: now,
        updated_at: now,
      },
    },

    // 4️⃣ Смешанное медиа (image + video → media, count > 3)
    {
      id: 4,
      chat: {
        uid: '4',
        username: 'john',
        nickname: 'john',
        first_name: 'John',
        last_name: 'Doe',
        avatar_url: '/images/avatars/avatar-4.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: false,
        was_online_at: now - 1000,
        is_in_contacts: true,
      },
      is_favorite: true,
      notifications: true,
      new_message_count: 0,
      name: 'John',
      chat_type: 'chat',
      chat_key: 'chat-4',
      last_activity_at: now,
      last_seen_message: { id: 4, uid: 'msg-4' },
      last_message: {
        id: 4,
        uid: 'msg-4',
        from_user: 'user-4',
        content: '',
        files_summary: {
          types: ['image', 'video'],
          count: 5,
        },
        has_replied_message: false,
        has_forwarded_message: false,
        new: false,
        created_at: now,
        updated_at: now,
      },
    },

    // 5️⃣ Текст + медиа (текст должен победить)
    {
      id: 5,
      chat: {
        uid: '5',
        username: 'anna',
        nickname: 'anna',
        first_name: 'Anna',
        last_name: 'White',
        avatar_url: '/images/avatars/avatar-5.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: false,
        was_online_at: now - 77000,
        is_in_contacts: true,
      },
      is_favorite: false,
      notifications: true,
      new_message_count: 0,
      name: 'Anna',
      chat_type: 'chat',
      chat_key: 'chat-5',
      last_activity_at: now,
      last_seen_message: { id: 5, uid: 'msg-5' },
      last_message: {
        id: 5,
        uid: 'msg-5',
        from_user: 'user-5',
        content: 'Смотри, что я нашла',
        files_summary: {
          types: ['image'],
          count: 2,
        },
        has_replied_message: false,
        has_forwarded_message: false,
        new: false,
        created_at: now,
        updated_at: now,
      },
    },

    // 6️⃣ Пересланный текст
    {
      id: 6,
      chat: {
        uid: '6',
        username: 'oleg',
        nickname: 'oleg',
        first_name: 'Oleg',
        last_name: 'Petrov',
        avatar_url: '/images/avatars/avatar-1.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: false,
        was_online_at: now - 102700,
        is_in_contacts: true,
      },
      is_favorite: false,
      notifications: true,
      new_message_count: 0,
      name: 'Oleg',
      chat_type: 'chat',
      chat_key: 'chat-6',
      last_activity_at: now,
      last_seen_message: { id: 6, uid: 'msg-6' },
      last_message: {
        id: 6,
        uid: 'msg-6',
        from_user: 'user-6',
        content: 'Это пересланное сообщение',
        files_summary: null,
        has_replied_message: false,
        has_forwarded_message: true,
        new: false,
        created_at: now,
        updated_at: now,
      },
    },

    // 7️⃣ Ответ на сообщение (reply → обычный текст)
    {
      id: 7,
      chat: {
        uid: '7',
        username: 'max',
        nickname: 'max',
        first_name: 'Max',
        last_name: 'Stone',
        avatar_url: '/images/avatars/avatar-2.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: false,
        was_online_at: now - 302700,
        is_in_contacts: true,
      },
      is_favorite: false,
      notifications: true,
      new_message_count: 0,
      name: 'Max',
      chat_type: 'chat',
      chat_key: 'chat-7',
      last_activity_at: now,
      last_seen_message: { id: 7, uid: 'msg-7' },
      last_message: {
        id: 7,
        uid: 'msg-7',
        from_user: 'user-7',
        content: 'Да, согласен',
        files_summary: null,
        has_replied_message: true,
        has_forwarded_message: false,
        new: false,
        created_at: now,
        updated_at: now,
      },
    },

    // 8️⃣ Новые сообщения → счётчик, фаворит скрыт
    {
      id: 8,
      chat: {
        uid: '8',
        username: 'sergey',
        nickname: 'sergey',
        first_name: 'Sergey',
        last_name: 'Kozlov',
        avatar_url: '/images/avatars/avatar-3.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: false,
        was_online_at: now - 202700,
        is_in_contacts: true,
      },
      is_favorite: true,
      notifications: true,
      new_message_count: 59,
      name: 'Sergey',
      chat_type: 'chat',
      chat_key: 'chat-8',
      last_activity_at: now,
      last_seen_message: { id: 8, uid: 'msg-8' },
      last_message: {
        id: 8,
        uid: 'msg-8',
        from_user: 'user-8',
        content:
          'Привет. Я оставил две стремянки и два шуруповёрта. Один в кейсе, а другой просто так. Одна батарейка может кончиться, тогда будете одним добивать. Воды с собой возьмите, там ничего уже не осталось.',
        files_summary: null,
        has_replied_message: false,
        has_forwarded_message: false,
        new: true,
        created_at: now,
        updated_at: now,
      },
    },
    {
      id: 9,
      chat: {
        uid: '9',
        username: 'Vlad',
        nickname: 'Vlad',
        first_name: 'Влад',
        last_name: 'Ляшев',
        avatar_url: '/images/avatars/avatar-1.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: true,
        was_online_at: 0,
        is_in_contacts: true,
      },
      is_favorite: true,
      notifications: true,
      new_message_count: 9,
      name: 'Vlad',
      chat_type: 'chat',
      chat_key: 'chat-9',
      last_activity_at: now,
      last_seen_message: { id: 9, uid: 'msg-9' },
      last_message: {
        id: 9,
        uid: 'msg-9',
        from_user: 'user-9',
        content: 'Привет! Как дела.',
        files_summary: null,
        has_replied_message: false,
        has_forwarded_message: false,
        new: true,
        created_at: now,
        updated_at: now,
      },
    },
    {
      id: 10,
      chat: {
        uid: '10',
        username: 'Anna',
        nickname: 'Anna',
        first_name: 'Анна',
        last_name: 'Киреева',
        avatar_url: '/images/avatars/avatar-2.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: false,
        was_online_at: now - 2700,
        is_in_contacts: true,
      },
      is_favorite: true,
      notifications: true,
      new_message_count: 10,
      name: 'Anna',
      chat_type: 'chat',
      chat_key: 'chat-10',
      last_activity_at: now,
      last_seen_message: { id: 10, uid: 'msg-10' },
      last_message: {
        id: 10,
        uid: 'msg-10',
        from_user: 'user-10',
        content: 'Hello!',
        files_summary: null,
        has_replied_message: false,
        has_forwarded_message: false,
        new: true,
        created_at: now,
        updated_at: now,
      },
    },
    {
      id: 11,
      chat: {
        uid: '11',
        username: 'Maksim',
        nickname: 'Maksim',
        first_name: 'Максим',
        last_name: 'Орлов',
        avatar_url: '/images/avatars/avatar-3.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: false,
        was_online_at: null,
        is_in_contacts: true,
      },
      is_favorite: true,
      notifications: true,
      new_message_count: 1,
      name: 'Maksim',
      chat_type: 'chat',
      chat_key: 'chat-11',
      last_activity_at: now,
      last_seen_message: { id: 11, uid: 'msg-11' },
      last_message: {
        id: 11,
        uid: 'msg-11',
        from_user: 'user-11',
        content: 'Давай встретимся!',
        files_summary: null,
        has_replied_message: false,
        has_forwarded_message: false,
        new: true,
        created_at: now,
        updated_at: now,
      },
    },
    {
      id: 12,
      chat: {
        uid: '12',
        username: 'Ekaterina',
        nickname: 'Ekaterina',
        first_name: 'Екатерина',
        last_name: 'Смирнова',
        avatar_url: '/images/avatars/avatar-4.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: false,
        was_online_at: now - 1302700,
        is_in_contacts: true,
      },
      is_favorite: true,
      notifications: true,
      new_message_count: 3,
      name: 'Ekaterina',
      chat_type: 'chat',
      chat_key: 'chat-12',
      last_activity_at: now,
      last_seen_message: { id: 12, uid: 'msg-12' },
      last_message: {
        id: 12,
        uid: 'msg-12',
        from_user: 'user-12',
        content: 'AAAAAAAAAAAAAAA',
        files_summary: null,
        has_replied_message: false,
        has_forwarded_message: false,
        new: true,
        created_at: now,
        updated_at: now,
      },
    },
    {
      id: 13,
      chat: {
        uid: '13',
        username: 'Ily',
        nickname: 'Ily',
        first_name: 'Илья',
        last_name: 'Романов',
        avatar_url: '/images/avatars/avatar-5.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: false,
        was_online_at: now - 11302700,
        is_in_contacts: true,
      },
      is_favorite: true,
      notifications: true,
      new_message_count: 2,
      name: 'Ily',
      chat_type: 'chat',
      chat_key: 'chat-13',
      last_activity_at: now,
      last_seen_message: { id: 13, uid: 'msg-13' },
      last_message: {
        id: 13,
        uid: 'msg-13',
        from_user: 'user-13',
        content: 'BBBBBBBDD',
        files_summary: null,
        has_replied_message: false,
        has_forwarded_message: false,
        new: true,
        created_at: now,
        updated_at: now,
      },
    },
    {
      id: 14,
      chat: {
        uid: '14',
        username: 'Maria',
        nickname: 'Ily',
        first_name: 'Мария',
        last_name: 'Соколова',
        avatar_url: '/images/avatars/avatar-2.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: false,
        was_online_at: now - 111302700,
        is_in_contacts: true,
      },
      is_favorite: true,
      notifications: true,
      new_message_count: 0,
      name: 'Maria',
      chat_type: 'chat',
      chat_key: 'chat-14',
      last_activity_at: now,
      last_seen_message: { id: 14, uid: 'msg-14' },
      last_message: {
        id: 14,
        uid: 'msg-14',
        from_user: 'user-14',
        content: 'MMMMMM',
        files_summary: null,
        has_replied_message: false,
        has_forwarded_message: false,
        new: true,
        created_at: now,
        updated_at: now,
      },
    },
    {
      id: 15,
      chat: {
        uid: '15',
        username: 'Artem',
        nickname: 'Artem',
        first_name: 'Артём',
        last_name: 'Кузнецов',
        avatar_url: '/images/avatars/avatar-3.svg',
        avatar_webp_url: '',
        is_blocked: false,
        is_online: false,
        was_online_at: now - 311302700,
        is_in_contacts: true,
      },
      is_favorite: true,
      notifications: true,
      new_message_count: 0,
      name: 'Artem',
      chat_type: 'chat',
      chat_key: 'chat-15',
      last_activity_at: now,
      last_seen_message: { id: 15, uid: 'msg-15' },
      last_message: {
        id: 15,
        uid: 'msg-14',
        from_user: 'user-15',
        content: 'AAAAAAAA',
        files_summary: null,
        has_replied_message: false,
        has_forwarded_message: false,
        new: true,
        created_at: now,
        updated_at: now,
      },
    },
  ] as ChatList[],
};

export const CONTACTS_LIST = [
  {
    uid: '1',
    avatar: '/images/avatars/avatar-1.svg',
    first_name: 'Влад',
    last_name: 'Ляшев',
    status: 0,
  },
  {
    uid: '2',
    avatar: '/images/avatars/avatar-2.svg',
    first_name: 'Анна',
    last_name: 'Киреева',
    status: 0.5,
  },
  {
    uid: '3',
    avatar: '/images/avatars/avatar-3.svg',
    first_name: 'Максим',
    last_name: 'Орлов',
    status: 5,
  },
  {
    uid: '4',
    avatar: '/images/avatars/avatar-4.svg',
    first_name: 'Екатерина',
    last_name: 'Смирнова',
    status: 18,
  },
  {
    uid: '5',
    avatar: '/images/avatars/avatar-5.svg',
    first_name: 'Илья',
    last_name: 'Романов',
    status: 42,
  },
  {
    uid: '6',
    avatar: '/images/avatars/avatar-1.svg',
    first_name: 'Мария',
    last_name: 'Соколова',
    status: 60,
  },
  {
    uid: '7',
    avatar: '/images/avatars/avatar-2.svg',
    first_name: 'Артём',
    last_name: 'Кузнецов',
    status: 120,
  },
  {
    uid: '8',
    avatar: '/images/avatars/avatar-3.svg',
    first_name: 'Ольга',
    last_name: 'Павлова',
    status: 300,
  },
  {
    uid: '9',
    avatar: '/images/avatars/avatar-4.svg',
    first_name: 'Денис',
    last_name: 'Фёдоров',
    status: 720,
  },
  {
    uid: '10',
    avatar: '/images/avatars/avatar-5.svg',
    first_name: 'Наталья',
    last_name: 'Иванова',
    status: 1380,
  },
  {
    uid: '11',
    avatar: '/images/avatars/avatar-1.svg',
    first_name: 'Павел',
    last_name: 'Мельников',
    status: 1440,
  },
  {
    uid: '12',
    avatar: '/images/avatars/avatar-2.svg',
    first_name: 'Юлия',
    last_name: 'Захарова',
    status: 1800,
  },
  {
    uid: '13',
    avatar: '/images/avatars/avatar-3.svg',
    first_name: 'Сергей',
    last_name: 'Белов',
    status: 2400,
  },
  {
    uid: '14',
    avatar: '/images/avatars/avatar-4.svg',
    first_name: 'Алина',
    last_name: 'Волкова',
    status: 3000,
  },
  {
    uid: '15',
    avatar: '/images/avatars/avatar-5.svg',
    first_name: 'Роман',
    last_name: 'Гусев',
    status: 4320,
  },
  {
    uid: '16',
    avatar: '/images/avatars/avatar-1.svg',
    first_name: 'Елена',
    last_name: 'Калинина',
    status: 7200,
  },
  {
    uid: '17',
    avatar: '/images/avatars/avatar-2.svg',
    first_name: 'Алексей',
    last_name: 'Морозов',
    status: 10080,
  },
  {
    uid: '18',
    avatar: '/images/avatars/avatar-3.svg',
    first_name: 'Дарья',
    last_name: 'Никитина',
    status: 20160,
  },
  {
    uid: '19',
    avatar: '/images/avatars/avatar-4.svg',
    first_name: 'Кирилл',
    last_name: 'Петров',
    status: 43200,
  },
  {
    uid: '20',
    avatar: '/images/avatars/avatar-5.svg',
    first_name: 'Полина',
    last_name: 'Андреева',
    status: 86400,
  },
];
